[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

remappings = [
    "@eigenlayer/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/script/",
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
    "@credible-squaring/=src/",
    "@openzeppelin/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/"
]

gas_reports = ["*"]

# A list of ignored solc error codes

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.12'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky_fork = "${HOLESKY_FORK_RPC_URL}"
sepolia_fork = "${SEPOLIA_FORK_RPC_URL}"

[etherscan]
holesky = { key = "8GWD6PI9JF9PUERQ9JMADRD4SKMEVE3EQV"}
sepolia = { key = "8GWD6PI9JF9PUERQ9JMADRD4SKMEVE3EQV"}

